// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Message.pb.h"
// @@protoc_insertion_point(imports)

@implementation MessageRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [MessageRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface Message ()
@property SInt32 messageType;
@property (strong) NSString* messageId;
@property (strong) NSString* version;
@property (strong) NSString* header;
@property (strong) NSString* body;
@end

@implementation Message

- (BOOL) hasMessageType {
  return !!hasMessageType_;
}
- (void) setHasMessageType:(BOOL) _value_ {
  hasMessageType_ = !!_value_;
}
@synthesize messageType;
- (BOOL) hasMessageId {
  return !!hasMessageId_;
}
- (void) setHasMessageId:(BOOL) _value_ {
  hasMessageId_ = !!_value_;
}
@synthesize messageId;
- (BOOL) hasVersion {
  return !!hasVersion_;
}
- (void) setHasVersion:(BOOL) _value_ {
  hasVersion_ = !!_value_;
}
@synthesize version;
- (BOOL) hasHeader {
  return !!hasHeader_;
}
- (void) setHasHeader:(BOOL) _value_ {
  hasHeader_ = !!_value_;
}
@synthesize header;
- (BOOL) hasBody {
  return !!hasBody_;
}
- (void) setHasBody:(BOOL) _value_ {
  hasBody_ = !!_value_;
}
@synthesize body;
- (instancetype) init {
  if ((self = [super init])) {
    self.messageType = 0;
    self.messageId = @"";
    self.version = @"";
    self.header = @"";
    self.body = @"";
  }
  return self;
}
static Message* defaultMessageInstance = nil;
+ (void) initialize {
  if (self == [Message class]) {
    defaultMessageInstance = [[Message alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultMessageInstance;
}
- (instancetype) defaultInstance {
  return defaultMessageInstance;
}
- (BOOL) isInitialized {
  if (!self.hasMessageType) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasMessageType) {
    [output writeInt32:1 value:self.messageType];
  }
  if (self.hasMessageId) {
    [output writeString:2 value:self.messageId];
  }
  if (self.hasVersion) {
    [output writeString:3 value:self.version];
  }
  if (self.hasHeader) {
    [output writeString:4 value:self.header];
  }
  if (self.hasBody) {
    [output writeString:5 value:self.body];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasMessageType) {
    size_ += computeInt32Size(1, self.messageType);
  }
  if (self.hasMessageId) {
    size_ += computeStringSize(2, self.messageId);
  }
  if (self.hasVersion) {
    size_ += computeStringSize(3, self.version);
  }
  if (self.hasHeader) {
    size_ += computeStringSize(4, self.header);
  }
  if (self.hasBody) {
    size_ += computeStringSize(5, self.body);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (Message*) parseFromData:(NSData*) data {
  return (Message*)[[[Message builder] mergeFromData:data] build];
}
+ (Message*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message*)[[[Message builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Message*) parseFromInputStream:(NSInputStream*) input {
  return (Message*)[[[Message builder] mergeFromInputStream:input] build];
}
+ (Message*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message*)[[[Message builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Message*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Message*)[[[Message builder] mergeFromCodedInputStream:input] build];
}
+ (Message*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message*)[[[Message builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MessageBuilder*) builder {
  return [[MessageBuilder alloc] init];
}
+ (MessageBuilder*) builderWithPrototype:(Message*) prototype {
  return [[Message builder] mergeFrom:prototype];
}
- (MessageBuilder*) builder {
  return [Message builder];
}
- (MessageBuilder*) toBuilder {
  return [Message builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasMessageType) {
    [output appendFormat:@"%@%@: %@\n", indent, @"messageType", [NSNumber numberWithInteger:self.messageType]];
  }
  if (self.hasMessageId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"messageId", self.messageId];
  }
  if (self.hasVersion) {
    [output appendFormat:@"%@%@: %@\n", indent, @"version", self.version];
  }
  if (self.hasHeader) {
    [output appendFormat:@"%@%@: %@\n", indent, @"header", self.header];
  }
  if (self.hasBody) {
    [output appendFormat:@"%@%@: %@\n", indent, @"body", self.body];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  if (self.hasMessageType) {
    [dictionary setObject: [NSNumber numberWithInteger:self.messageType] forKey: @"messageType"];
  }
  if (self.hasMessageId) {
    [dictionary setObject: self.messageId forKey: @"messageId"];
  }
  if (self.hasVersion) {
    [dictionary setObject: self.version forKey: @"version"];
  }
  if (self.hasHeader) {
    [dictionary setObject: self.header forKey: @"header"];
  }
  if (self.hasBody) {
    [dictionary setObject: self.body forKey: @"body"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[Message class]]) {
    return NO;
  }
  Message *otherMessage = other;
  return
      self.hasMessageType == otherMessage.hasMessageType &&
      (!self.hasMessageType || self.messageType == otherMessage.messageType) &&
      self.hasMessageId == otherMessage.hasMessageId &&
      (!self.hasMessageId || [self.messageId isEqual:otherMessage.messageId]) &&
      self.hasVersion == otherMessage.hasVersion &&
      (!self.hasVersion || [self.version isEqual:otherMessage.version]) &&
      self.hasHeader == otherMessage.hasHeader &&
      (!self.hasHeader || [self.header isEqual:otherMessage.header]) &&
      self.hasBody == otherMessage.hasBody &&
      (!self.hasBody || [self.body isEqual:otherMessage.body]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasMessageType) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.messageType] hash];
  }
  if (self.hasMessageId) {
    hashCode = hashCode * 31 + [self.messageId hash];
  }
  if (self.hasVersion) {
    hashCode = hashCode * 31 + [self.version hash];
  }
  if (self.hasHeader) {
    hashCode = hashCode * 31 + [self.header hash];
  }
  if (self.hasBody) {
    hashCode = hashCode * 31 + [self.body hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface MessageBuilder()
@property (strong) Message* resultMessage;
@end

@implementation MessageBuilder
@synthesize resultMessage;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultMessage = [[Message alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultMessage;
}
- (MessageBuilder*) clear {
  self.resultMessage = [[Message alloc] init];
  return self;
}
- (MessageBuilder*) clone {
  return [Message builderWithPrototype:resultMessage];
}
- (Message*) defaultInstance {
  return [Message defaultInstance];
}
- (Message*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Message*) buildPartial {
  Message* returnMe = resultMessage;
  self.resultMessage = nil;
  return returnMe;
}
- (MessageBuilder*) mergeFrom:(Message*) other {
  if (other == [Message defaultInstance]) {
    return self;
  }
  if (other.hasMessageType) {
    [self setMessageType:other.messageType];
  }
  if (other.hasMessageId) {
    [self setMessageId:other.messageId];
  }
  if (other.hasVersion) {
    [self setVersion:other.version];
  }
  if (other.hasHeader) {
    [self setHeader:other.header];
  }
  if (other.hasBody) {
    [self setBody:other.body];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (MessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (MessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setMessageType:[input readInt32]];
        break;
      }
      case 18: {
        [self setMessageId:[input readString]];
        break;
      }
      case 26: {
        [self setVersion:[input readString]];
        break;
      }
      case 34: {
        [self setHeader:[input readString]];
        break;
      }
      case 42: {
        [self setBody:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasMessageType {
  return resultMessage.hasMessageType;
}
- (SInt32) messageType {
  return resultMessage.messageType;
}
- (MessageBuilder*) setMessageType:(SInt32) value {
  resultMessage.hasMessageType = YES;
  resultMessage.messageType = value;
  return self;
}
- (MessageBuilder*) clearMessageType {
  resultMessage.hasMessageType = NO;
  resultMessage.messageType = 0;
  return self;
}
- (BOOL) hasMessageId {
  return resultMessage.hasMessageId;
}
- (NSString*) messageId {
  return resultMessage.messageId;
}
- (MessageBuilder*) setMessageId:(NSString*) value {
  resultMessage.hasMessageId = YES;
  resultMessage.messageId = value;
  return self;
}
- (MessageBuilder*) clearMessageId {
  resultMessage.hasMessageId = NO;
  resultMessage.messageId = @"";
  return self;
}
- (BOOL) hasVersion {
  return resultMessage.hasVersion;
}
- (NSString*) version {
  return resultMessage.version;
}
- (MessageBuilder*) setVersion:(NSString*) value {
  resultMessage.hasVersion = YES;
  resultMessage.version = value;
  return self;
}
- (MessageBuilder*) clearVersion {
  resultMessage.hasVersion = NO;
  resultMessage.version = @"";
  return self;
}
- (BOOL) hasHeader {
  return resultMessage.hasHeader;
}
- (NSString*) header {
  return resultMessage.header;
}
- (MessageBuilder*) setHeader:(NSString*) value {
  resultMessage.hasHeader = YES;
  resultMessage.header = value;
  return self;
}
- (MessageBuilder*) clearHeader {
  resultMessage.hasHeader = NO;
  resultMessage.header = @"";
  return self;
}
- (BOOL) hasBody {
  return resultMessage.hasBody;
}
- (NSString*) body {
  return resultMessage.body;
}
- (MessageBuilder*) setBody:(NSString*) value {
  resultMessage.hasBody = YES;
  resultMessage.body = value;
  return self;
}
- (MessageBuilder*) clearBody {
  resultMessage.hasBody = NO;
  resultMessage.body = @"";
  return self;
}
@end


// @@protoc_insertion_point(global_scope)
